# Generated by Django 3.2 on 2021-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('borrowered', 'borrowered')], default='available', max_length=10),
        ),
    ]
